version: '3'
services:
#database container
  postgresdb:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=nikhil382
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecommerce_db
    volumes:
      - database:/var/lib/postgresql/data
# webapp container
  app:
    image: nikhil382/ecommerce-gin-clean-arch
    ports:
      - 8000:8000
    environment:
      - DB_HOST=postgresdb
      - DB_NAME=ecommerce_db
      - DB_USER=nikhil382
      - DB_PASSWORD=password
      - DB_PORT=5432
    depends_on:
      - postgresdb

# pg admin for showing the database on GUI
  # pg-admin:
  #   image:  dpage/pgadmin4
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=nikhil@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=password

# storing datas on docker side
volumes:
  database:
    driver: local
