definitions:
  domain.User:
    properties:
      age:
        type: integer
      block_status:
        type: boolean
      email:
        type: string
      first_name:
        maxLength: 50
        minLength: 2
        type: string
      id:
        type: integer
      last_name:
        maxLength: 50
        minLength: 1
        type: string
      password:
        type: string
      phone:
        maxLength: 10
        minLength: 10
        type: string
      user_name:
        maxLength: 15
        minLength: 3
        type: string
    required:
    - age
    - email
    - first_name
    - last_name
    - password
    - phone
    - user_name
    type: object
  helper.LoginStruct:
    properties:
      email:
        type: string
      password:
        maxLength: 30
        minLength: 5
        type: string
      phone:
        maxLength: 10
        minLength: 10
        type: string
      user_name:
        maxLength: 15
        minLength: 3
        type: string
    required:
    - password
    type: object
  helper.OTPLoginStruct:
    properties:
      email:
        type: string
      phone:
        maxLength: 10
        minLength: 10
        type: string
      user_name:
        maxLength: 16
        minLength: 3
        type: string
    type: object
  helper.OTPVerifyStruct:
    properties:
      id:
        type: integer
      otp:
        maxLength: 8
        minLength: 4
        type: string
    required:
    - id
    - otp
    type: object
  helper.ReqAddress:
    properties:
      area:
        type: string
      city:
        type: string
      country_id:
        type: integer
      house:
        type: string
      id:
        type: integer
      is_default:
        type: boolean
      land_mark:
        type: string
      name:
        maxLength: 50
        minLength: 2
        type: string
      phone_number:
        maxLength: 10
        minLength: 10
        type: string
      pincode:
        type: integer
    required:
    - country_id
    - house
    - land_mark
    - name
    - phone_number
    - pincode
    type: object
info:
  contact: {}
paths:
  /login:
    get:
      description: Enter this fields on login page post
      operationId: LoginGet
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.LoginStruct'
      security:
      - ApiKeyAuth: []
      summary: to get the json format for login
      tags:
      - login
    post:
      description: Enter user_name/phone/email with password
      operationId: LoginPost
      parameters:
      - description: Input Field
        in: body
        name: inputs
        required: true
        schema:
          $ref: '#/definitions/helper.LoginStruct'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully Loged In
        "400":
          description: faild to login
        "500":
          description: faild to generat JWT
      security:
      - ApiKeyAuth: []
      summary: api for user login
      tags:
      - login
  /login-otp-send:
    post:
      description: user can enter email/user_name/phone will send an otp to user phone
      operationId: LoginOtpSend
      parameters:
      - description: Input Field
        in: body
        name: inputs
        required: true
        schema:
          $ref: '#/definitions/helper.OTPLoginStruct'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully Otp Send to registered number
        "400":
          description: Enter input properly
        "500":
          description: Faild to send otp
      security:
      - ApiKeyAuth: []
      summary: api for user login with otp
      tags:
      - login-otp
  /login-otp-verify:
    post:
      description: enter your otp that send to your registered number
      operationId: LoginOtpVerify
      parameters:
      - description: Input Field
        in: body
        name: inputs
        required: true
        schema:
          $ref: '#/definitions/helper.OTPVerifyStruct'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully Logged In
        "400":
          description: Invalid Otp
        "500":
          description: Faild to generate JWT
      security:
      - ApiKeyAuth: []
      summary: varify user login otp
      tags:
      - login-otp
  /logout:
    post:
      description: user can logout
      operationId: Logout
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logout
      security:
      - ApiKeyAuth: []
      summary: api for user to lgout
      tags:
      - logout
  /profile/address:
    post:
      description: get a new address from user to store the the database
      operationId: AddAddress
      parameters:
      - description: Input Field
        in: body
        name: inputs
        required: true
        schema:
          $ref: '#/definitions/helper.ReqAddress'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully address added
        "400":
          description: can't add the user addres
      security:
      - ApiKeyAuth: []
      summary: api for adding a new address for user
      tags:
      - address
  /signup:
    get:
      description: user can see what are the fields to enter to create a new account
      operationId: SignUpGet
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
      security:
      - ApiKeyAuth: []
      summary: api for user to signup page
      tags:
      - signup
    post:
      description: user can send user details and validate and create new account
      operationId: SignUpPost
      produces:
      - application/json
      responses:
        "200":
          description: Successfully account created
        "400":
          description: Faild to create account
      security:
      - ApiKeyAuth: []
      summary: api for user to post the user details
      tags:
      - signup
swagger: "2.0"
